solution
mate-academy/react_redux-list-of-posts pull request #101
Opened 2022-01-30 17:30 UTC by Bohdan996

[DEMO LINK](https://Bohdan996.github.io/react_redux-list-of-posts/)

2022-01-31 16:27 UTC, vkryvytskyy requested changes

2022-01-31 16:27 UTC, vkryvytskyy commented on src/App.tsx
> +  const postQuery = searchParams.get('postId') || '';
А чем тебе не подходит undefined, который оттуда если что вернется?

2022-01-31 16:27 UTC, vkryvytskyy commented on src/components/NewComment/NewComment.tsx
> +  const [body, setBody] = useState('');
Объедини в один state с объектом внутри

2022-01-31 20:25 UTC, Bohdan996 commented on src/App.tsx
> +  const postQuery = searchParams.get('postId') || '';
![image](https://user-images.githubusercontent.com/79786405/151867372-d3e1ee40-6037-4e72-bf4b-4f0d98481e25.png)
для некоторых параметров не так удобно как string

2022-02-01 11:58 UTC, vkryvytskyy approved these changes

2022-02-01 11:58 UTC, vkryvytskyy commented on src/App.tsx
> +  const getFilteredPosts = useMemo(() => {
просто `filteredPosts`, это ж не функция, а массив в этой переменной хранится

2022-02-01 11:58 UTC, vkryvytskyy commented on src/App.tsx
> +        {}
Это наверное можно удалить

2022-11-26 14:19 UTC, closed without merging