Solution
mate-academy/react_redux-list-of-posts pull request #125
Opened 2022-06-06 14:44 UTC by YegorKochetkov

[DEMO LINK](https://YegorKochetkov.github.io/react_redux-list-of-posts/)

2022-06-06 18:06 UTC, Anastasiia-Svintsova requested changes
не відкривається посилання
![Снимок экрана 2022-06-06 210604](https://user-images.githubusercontent.com/99403198/172219646-007d2ba5-408f-4247-a9bc-2efd4d93d84c.png)

2022-06-06 18:32 UTC, YegorKochetkov commented
блин, не глянул что деплой не завершился)

2022-06-07 10:10 UTC, Anastasiia-Svintsova approved these changes
Good

2022-06-07 10:10 UTC, Anastasiia-Svintsova commented on src/components/NewCommentForm/NewCommentForm.tsx
> +  const [isValidMessage, setIsValidMessage] = useState(true);
Можна було б винести в Redux

2022-06-13 08:41 UTC, MaksimusCRS commented on src/components/PostDetails/PostDetails.tsx
> +      </div>
Agree, fix it)

2022-06-13 08:49 UTC, MaksimusCRS approved these changes
Looks cool, well done!

2022-06-13 08:49 UTC, MaksimusCRS commented on src/App.scss
> +}
it must be in normalize.scss

2022-06-13 08:49 UTC, MaksimusCRS commented on src/api/comments.ts
> +// not used so as not to torment the training server
😄

2022-06-13 08:49 UTC, MaksimusCRS commented on src/components/NewCommentForm/NewCommentForm.scss
> +    padding: 10px 5px;
try to use only 1 unit of measure, u can read about rem-calc

2022-06-13 08:49 UTC, MaksimusCRS commented on src/components/UserSelect/UserSelect.tsx
> +        <option value="10">Leanne Graham</option>
Use map here

2022-06-13 08:49 UTC, MaksimusCRS commented on src/store/index.ts
>   */
Remove it

2022-11-01 23:32 UTC, closed without merging