solution
mate-academy/react_redux-list-of-posts pull request #680
Opened 2024-08-04 13:57 UTC by BodyaKutsyk

[DEMO LINK](https://BodyaKutsyk.github.io/react_redux-list-of-posts/)

2024-08-04 20:21 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's make your code better

2024-08-04 20:21 UTC, volodymyr-soltys97 commented on src/components/Comment.tsx
> +          {comment.name}
Use destructuring for `comment`

2024-08-04 20:21 UTC, volodymyr-soltys97 commented on src/features/comments.ts
> +      // eslint-disable-next-line no-param-reassign
Turn off the linter for that file at the top and delete it everywhere
```suggestion
```

2024-08-05 07:04 UTC, etojeDenys approved these changes
lgtm

2026-07-11 18:50 UTC, closed without merging