Develop
mate-academy/react_redux-list-of-posts pull request #695
Opened 2024-08-22 16:02 UTC by GeorgeSavostikov

[DEMO LINK](https://georgesavostikov.github.io/react_redux-list-of-posts/)

2024-08-22 16:43 UTC, TarasHoliuk requested changes
GJ 👍  But you should use async thunk in this task

2024-08-22 16:43 UTC, TarasHoliuk commented on src/App.tsx
> +      .finally(() => dispatch(postsActions.setLoaded(true)));
In this task, you should use `createAsyncThunk` to handle promise states (where you do it) in the reducer

2024-08-22 16:43 UTC, TarasHoliuk commented on src/app/store.ts
>      counter: counterReducer,
delete counter - it was an example

2024-08-23 09:20 UTC, volodymyr-soltys97 requested changes
Good job! 👍 
Let's improve your code
The comment cannot be only spaces, need to fix it 
<img width="698" alt="image" src="https://github.com/user-attachments/assets/74886bcb-5e10-4cf9-b2c5-ff4bdf03e3ac">

Add a correct type to input of email 
<img width="1108" alt="image" src="https://github.com/user-attachments/assets/5b421cfd-5e46-41cd-96df-682eb2903156">

2024-08-23 10:32 UTC, volodymyr-soltys97 approved these changes
Good job! 👍

2026-04-30 07:25 UTC, closed without merging