Develop
mate-academy/react_redux-list-of-posts pull request #698
Opened 2024-09-02 10:40 UTC by RomanPerepelkin

https://RomanPerepelkin.github.io/react_redux-list-of-posts/

2024-09-02 15:55 UTC, TarasHoliuk requested changes
Great job!

Code looks good, but you left a lot of commented code - let's add a cleanup and remove it

2024-09-02 15:55 UTC, TarasHoliuk commented on src/features/users.ts
> +export const loadUser = createAsyncThunk('users/fetch', async () => {
```suggestion
export const loadUsers = createAsyncThunk('users/fetch', async () => {
```

2024-09-02 15:55 UTC, TarasHoliuk commented on src/components/PostDetails.tsx
> +  // const [comments, setComments] = useState<Comment[]>([]);
remove comments

2024-09-02 15:55 UTC, TarasHoliuk commented on src/components/PostDetails.tsx
> +// import { Post } from '../types/Post';
remove comments

fix all similar cases

2024-09-03 07:18 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code
1. You need to resolve merge conflicts 
<img width="522" alt="image" src="https://github.com/user-attachments/assets/6aa981f6-44f2-406e-a1ab-c81fa17ce153">

2. The comment cannot be only spaces 
<img width="677" alt="image" src="https://github.com/user-attachments/assets/33344d6f-3ac2-47db-9c73-7820017eb44c">

3. Add a correct type to input of email 
<img width="978" alt="image" src="https://github.com/user-attachments/assets/1902f352-a754-4e67-b6a6-ce22fe6bdd3c">

2024-09-03 10:43 UTC, RomanPerepelkin commented
Please tell me how to fix conflict

2024-09-03 12:10 UTC, anastasiiavorobiova requested changes
Please, ask questions in the chat or during the QA sessions. It's much more effective. Mentors can see your comments just once during the review

2024-09-04 09:54 UTC, closed without merging